### ISSUE TITLE
Bug in elastix_paramStruct2txt?

### ISSUE THREAD

**Issue by muellerflorian** [raacampbell13/matlab_elastix#17]
Dear Rob,

first, thanks for putting together this project. 

I think there is a small bug in the function elastix_paramStruct2txt.m, when writting out logical values. Here both only true gets written in the text file. I think line 72 should be 

 str = sprintf('(%s "false")\n',param);

Best
Florian

**Comment by raacampbell** [comment]
Ooh, nasty bug. Thanks.
00c5039
