### ISSUE TITLE
The Example Code Failed

### ISSUE THREAD

**Issue by mylyu** [raacampbell13/matlab_elastix#18]
Hi,

It seems you example code does not work, possibly because of your recent update.

> Undefined variable "mElastixYML" or class "mElastixYML.yaml.ReadYaml".
> 
> Error in elastixYAML2struct (line 40)
> yml=mElastixYML.yaml.ReadYaml(fname);
> 
> Error in elastix_parameter_write (line 56)
> params=elastixYAML2struct(YAML); %Default params from a user-supplied YAML or the default YAML
> 
> Error in elastix (line 195)
>         elastix_parameter_write(paramFname{ii},paramFile,paramstruct(ii))
> 
> Error in example_2D_affine_alpha>runExampleLena (line 52)
> 	reg=elastix(lenaTrans,lena,[],'elastix_default.yml','paramstruct',p);
> 
> Error in example_2D_affine_alpha (line 40)
> 	runExampleLena(lenaTrans,lena,p,ind)
>  
> 40  yml=mElastixYML.yaml.ReadYaml(fname);

**Comment by raacampbell** [comment]
Yes, that's the problem. Sorry--I thought I tested it. I'll come up with a fix.

**Comment by raacampbell** [comment]
In the mean time I reverted the master branch back to a working version, so just pull it again.

**Comment by raacampbell** [comment]
`example_invert` tested and works

**Comment by raacampbell** [comment]
examples in elastix dir seem fine too. Presumbably this is all fixed now?
