### ISSUE TITLE
No function or variable 'Elastix' is defined.

### ISSUE THREAD

**Issue by Tiantian089** [raacampbell13/matlab_elastix#24]
Hi,
I've followed the guidance of "Getting started". But I ran into the error:No function or variable 'Elastix' is defined when I ran the examples in MelastiX_examples.

未定义函数或变量 'elastix'。

出错 example_2D_affine_alpha>runExampleLena (line 52)
    reg=elastix(lenaTrans,lena,[],'elastix_default.yml','paramstruct',p);

出错 example_2D_affine_alpha (line 40)
    runExampleLena(lenaTrans,lena,p,ind)

Maybe do you konw which step I did wrong?  
Thank you very much!!

**Comment by raacampbell** [comment]
Did you add the `code` directory to your MATLAB path? If you did this correctly you will see the help text when you type `help elastix`. If you get an error instead, the functions are not in your MATLAB path.
