### ISSUE TITLE
Getting an error when using an Elastix parameter file

### ISSUE THREAD

**Issue by fabioeffe** [raacampbell13/matlab_elastix#26]
I am trying to use your wrapper with an Elastix parameter file (in .txt format) but I get this error:

Undefined function or variable 'paramFname'.
Error in elastix (line 247)
        copyfile(paramFname,outputDir)

Error in Register_images_FF2 (line 30)
        elastix(movingImage,fixedImage,outputDir,param_file);

Do you know what could cause it?

Thanks!

**Comment by raacampbell** [comment]
Please can you post your command history that led to this. It's impossible to diagnose what the problem is with so little information. Does the example code run? If so, I suspect it's a syntax error in calling the function.

**Comment by yuanci89** [comment]
I'm actually having the same issue now. I think it's somehow calling paramFname before that variable has been initialized.

> elastix(Angiorun,MPRresize,'C:\Users\yuanc\Dropbox (University of Michigan)\[ASNR ASFNR AI Workshop]\test\','C:\Users\yuanc\Dropbox (University of Michigan)\[ASNR ASFNR AI Workshop]\matlab_elastix-master\example_parameter_files\parameters_Rigid.txt')
> 
> Unrecognized function or variable 'paramFname'.
> 
> Error in elastix (line 247)
>         copyfile(paramFname,outputDir)
