### ISSUE TITLE
Unrecognized function or variable 'paramFname'.

### ISSUE THREAD

**Issue by yuanci89** [raacampbell13/matlab_elastix#29]
I'm trying to use this (for the first time), and I keep getting an error, I think it's trying to call 'paramFname' before it has been initialized.

I pasted what I'm seeing below.
Angiorun and MPRresize are both 512x512x497 matrices, I am basically just trying to do a rigid transformation.

> elastix(Angiorun,MPRresize,'C:\Users\yuanc\Dropbox (University of Michigan)\[ASNR ASFNR AI Workshop]\test\','C:\Users\yuanc\Dropbox (University of Michigan)\[ASNR ASFNR AI Workshop]\matlab_elastix-master\example_parameter_files\parameters_Rigid.txt')
> Unrecognized function or variable 'paramFname'.
> 
> Error in elastix (line 247)
>         copyfile(paramFname,outputDir)

**Comment by raacampbell** [comment]
Surprisingly you are the first person to try this use case. It was a bug that is now fixed: ba084dc4f31d128bebb27b46185eba0658c270f8

Thanks for providing a clear report of the problem.
